{
 "title": "Observabilidade - Flask App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Dados",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total de Jogadas de Dado (por valor)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (dice_value) (floor(increase(dice_rolls_total[5m])))"
      }
     ]
    },
    {
     "title": "Total de Jogadas de Dado (por valor)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (dice_value) (floor(increase(dice_rolls_total[5m])))"
      }
     ]
    },
    {
     "title": "Top 5 valores de dado mais jogados",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, floor(sum(increase(dice_rolls_total[5m])) by (dice_value)))"
      }
     ]
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "GET /",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 2 },
   "targets": [
    { "operation": "GET /", "service": "flask-dice-app" }
   ]
  },
  {
   "title": "GET /",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 2 },
   "targets": [
    { "operation": "GET /", "service": "flask-dice-app" }
   ]
  },
  {
   "title": "GET /health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 2 },
   "targets": [
    { "operation": "GET /health", "service": "flask-dice-app" }
   ]
  },
  {
   "title": "GET /history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 2 },
   "targets": [
    { "operation": "GET /history", "service": "flask-dice-app" }
   ]
  },
  {
   "title": "GET /metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 2 },
   "targets": [
    { "operation": "GET /metrics", "service": "flask-dice-app" }
   ]
  },
  {
   "title": "GET /metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 2 },
   "targets": [
    { "operation": "GET /metrics", "service": "flask-dice-app" }
   ]
  },
  {
   "title": "LPUSH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 2 },
   "targets": [
    { "operation": "LPUSH", "service": "flask-dice-app" }
   ]
  },
  {
   "title": "LRANGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 2 },
   "targets": [
    { "operation": "LRANGE", "service": "flask-dice-app" }
   ]
  },
  {
   "title": "Tempo de resposta P95 por rota",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket[1m])) by (le, http_target))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[30s])"
    }
   ]
  },
  {
   "title": "Erros 5xx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requisições por Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Tempo de Resposta - Histogram",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_bucket[1m])"
    }
   ]
  },
  {
   "title": "Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tráfego de rede por interface (entrada + saída) eth0 ",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) + rate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Espaço em disco",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes - node_filesystem_free_bytes) / 1024 / 1024 / 1024",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}